### ISSUE TITLE
MySQL/Doctrine : Connection refused

### ISSUE THREAD

**Issue by petegore** [petegore/calendmap#2]
While running `doctrine:database:create` I get an error : 
```
An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
```
It should come from the links between docker containers ; or the "root/root" dev credentials.

**Comment by petegore** [comment]
It seems that the issue was dur to several things : 
* no database was created
* no user was provided instead of root one
* the connection environment variable `DATABASE_URL` used by Symfony into `.env` file was wrong

I created a `mysql.env` file for my docker containers : 
```
# docker/mysql/mysql.env
# MySQL environment vars
MYSQL_ROOT_PASSWORD=root_pass
MYSQL_DATABASE=db_name
MYSQL_USER=user
MYSQL_PASSWORD=user_pass
DATABASE_URL=mysql://user:user_pass@mysqldbcontainer:3306/db_name
```

**Note : I tried to put variables into the DATABASE_URL in order to automatically take other env var values but it seems impossible : when PHP calls the DB, the var replacement doesn't work**

The `DATABASE_URL` will replace the one into the `app/.env` symfony file so the line should be commented into this file. I prefered to do this way to avoid writing DB credentials into 2 separates files. 

The `mysqldbcontainer` into the DB URL refers to the alias of the db container into the links of the php container : 

```yaml
# docker-compose.yml
services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./data/mysql:/var/lib/mysql"
        env_file:
            - docker/mysql/mysql.env
        container_name: calendmap-mysql
    php:
        build: docker/php7-fpm
        ports:
            - 9000:9000
        env_file:
            - docker/mysql/mysql.env
        links:
            - db:mysqldbcontainer
        volumes:
            - "./app:/var/www/symfony/app"
        container_name: calendmap-php
```

As you can see we found in this file two calls to the file `docker/mysql/mysql.env` that contains our env variables. This file is used by db container to create our db ; and by php container to know how to call the db without having to re-write our database credentials into symfony env files.
